In [2]:
import numpy as np

In [36]:
a = np.array([1, 2, 3], dtype=np.int16)
b = np.array([[1, 2, 3, 4], 
                [1, 5, 3, 4]])
print(a)

[1 2 3]


In [100]:
# Getting the number of dimensions
b.ndim

2

In [106]:
# getting the shape
b.shape

(2, 4)

In [158]:
# get the type
a.dtype

dtype('int32')

In [182]:
# get the size
a.nbytes

6

In [198]:
# Get a specific element => use [row][col] or [row, col]
print(b[0][1], b[0, 1])

2 2


In [212]:
# Get a specific row
print(b[0, :]) # same as print(b[0])

[1 2 3 4]


In [226]:
# Get a specific column
print(b[:, 1])

[2 5]


In [294]:
# getting a bit more fancy [startindex:endindex:stepsize]
# endindex is exclusive
b[0, 1:4:2]
b[0, 1:-1:1]

array([2, 3])

In [314]:
# changing elements
b[:, 3] = [10, 3] # the shape must match
b

array([[ 1,  2,  3, 10],
       [ 1,  5,  3,  3]])

### Initializing different types of Arrays

In [16]:
# all 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# all 1s matrix
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# any other number
np.full((2, 3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [44]:
# any other number(full_like)
np.full_like(a, 2)

array([2, 2, 2], dtype=int16)

In [60]:
# random decimal numbers
np.random.rand(4, 2)

array([[0.5516432 , 0.97018366],
       [0.12010163, 0.73344353],
       [0.10543607, 0.17692259],
       [0.29256472, 0.68770635]])

In [93]:
# random interger values
np.random.randint(7, 14, size=a.shape)

array([ 8, 11,  9])

In [101]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [137]:
# repeat an array 
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [185]:
output = np.ones((5, 5))
z = np.zeros((3, 3))
z[1, 1] = 9
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!

In [203]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
a

array([1, 2, 3])

#### Mathematics

In [238]:
a = np.array([1, 2, 3])
a + 2

array([3, 4, 5])

In [240]:
a - 2

array([-1,  0,  1])

In [242]:
a * 2

array([2, 4, 6])

In [244]:
a / 2

array([0.5, 1. , 1.5])

In [250]:
b = np.array([1, 0, 1])
a + b

array([2, 2, 4])

In [254]:
a ** 2

array([1, 4, 9])

In [274]:
# take sin of all values
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

### Linear Algebra

In [299]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [309]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [317]:
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [321]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [326]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [366]:
np.min(stats, axis=0) # axis=0 is for row and axis=1

array([1, 2, 3])

In [362]:
np.max(stats)

6

In [360]:
np.sum(stats)

21

In [24]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [46]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous 

#### Load data from a file

In [140]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') # makes a copy of the original
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking and Advanced Indexing

In [118]:
filedata[filedata > 50] # index based on boolean conditions

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [130]:
# You can index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
index = np.array([1, 2, 8])
a[index]

array([2, 3, 9])

In [138]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [162]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])